Development
kvnlay/members-only pull request #1
Opened 2019-04-26 09:55 UTC by kvnlay

2019-04-29 18:17 UTC, talihomz commented
Hi @Cena-JM @kvnlay.

Great work implementing members-only!! (Good work on the README as well!) I was able to build and run the code on my PC.
However, there were a couple of issues:
1. On running the app, the home page only had the Posts title with no other control on it.
![members-screen](https://user-images.githubusercontent.com/5684444/56917346-ee424c00-6ac3-11e9-88d3-9d10f9c17a80.png)

2. I was not able to create a user using the console, and always got a rollback:
![member-user](https://user-images.githubusercontent.com/5684444/56917364-fc906800-6ac3-11e9-900d-5f7aecb8b6d5.png)

Due to this, I had to stop the review prematurely. I followed the instructions on your README. Am I missing something?

2019-05-03 14:20 UTC, heyapricot requested changes
# The app logic isn't where it should be + authentication 🧠❓🔐
👋🏼 Hello Team! You are almost done. There are some thing in the project that need to be fixed. I've raised some issues and added comments. Please address all of them and once you are done submit a new code review request. Thanks! 

* To consider the project ‘complete’ it must meet the next points:
## General
- [x] The project has a descriptive README.md
## Features
### Authentication
- [x] The application uses the `bcrypt` gem for authentication ( You can use `User.authenticate(password)` )
### `Sessions`
- [x] The remember token is stored in a cookie
- [x] The application remembers the user with the stored remember token
- [x] You can `sign_out` of the application
### `Posts`
#### `:new`
- [x] The application can create posts (`:new`)
- [x] If a post is created successfully the application redirects to the post  `index` view
#### `:index`
- [x] The application can list all posts (`:index`)
- [x] A post's author is displayed only if you are signed in
## Models
### `User`
- [x] It has a `remember_token` field
- [x] A remember token is generated and encrypted with a `before_create` callback
## Controllers
### Application
- [x] It has a `current_user` method that uses the `||=` operator
### Posts
- [x] It uses `before_action` to restrict access to the `:new` and `:create` methods"
- [x] The `new` action uses the `current_user` method to build a post. E.g.

2019-05-03 14:20 UTC, heyapricot commented on app/controllers/posts_controller.rb
> +    @post.user_id = current_user.id
What about using `@post = current_user.post.build` instead of lines 16 an 17?

2019-05-03 14:20 UTC, heyapricot commented on app/helpers/sessions_helper.rb
> +end
Files in the `helpers` directory are more specifically `view helpers`
Having these methods defined in the helpers puts a lot of your logic on the views which is not good. 

Move the methods to the corresponding controller. If you need to have a method available between controllers you can define it on the `application_controller`

2019-05-03 14:20 UTC, heyapricot commented on app/helpers/sessions_helper.rb
> +end
http://codefol.io/posts/where-do-i-put-my-code-in-rails-updated/

2019-05-06 11:41 UTC, kvnlay commented
Hello @heyapricot, thanks for the review. We have made the suggested changes and await your response.

2019-05-10 23:03 UTC, heyapricot approved these changes
# You did it! 👍🏼
Great job team! Your application is working as intended. Yay!
No need from my side for further review. Lets' move to the next project 🚀

2019-05-11 00:39 UTC, merged